using System.Collections.Generic;

public class SD
{
    public IList<int> SequentialDigits(int low, int high)
    {
        // Stores every sequential-digit number within [low, high].
        List<int> retList = new List<int>();

        /*
         * Instead of checking every number from low to high,
         * create only numbers that can possibly be sequential.
         *
         * Examples:
         * startDigit = 1 -> 12, 123, 1234, ...
         * startDigit = 4 -> 45, 456, 4567, ...
         */
        for (int startDigit = 1; startDigit <= 9; startDigit++)
        {
            int number = 0;

            /*
             * Append the next consecutive digit each time.
             *
             * Example when startDigit is 3:
             * number = 3
             * number = 34
             * number = 345
             * number = 3456
             */
            for (int currentDigit = startDigit; currentDigit <= 9; currentDigit++)
            {
                number = number * 10 + currentDigit;

                /*
                 * A single digit is not considered a sequential-digit
                 * number for this LeetCode problem, so start checking
                 * after at least two digits have been added.
                 */
                if (currentDigit == startDigit)
                {
                    continue;
                }

                // Add the number only if it is inside the required range.
                if (number >= low && number <= high)
                {
                    retList.Add(number);
                }

                /*
                 * Adding more digits will only make this number larger,
                 * so there is no reason to continue this sequence once
                 * it has passed high.
                 */
                if (number > high)
                {
                    break;
                }
            }
        }

        /*
         * The numbers are generated by starting digit:
         * 12, 123, 1234, 23, 234, ...
         *
         * Therefore, sort them before returning because LeetCode
         * requires the result in ascending order.
         */
        retList.Sort();

        return retList;
    }
}
